temp6 = inject_int(4)
t = create_list(temp6)
temp1 = inject_int(1)
temp2 = inject_bool(True)
temp3 = inject_int(3)
temp4 = inject_int(4)
temp8 = inject_int(0)
temp9 = inject_int(2)
set_subscript(t,temp8,temp1)
set_subscript(t,temp1,temp2)
set_subscript(t,temp9,temp3)
set_subscript(t,temp3,temp4)
temp5 = inject_int(2)
temp7 = get_subscript(t,temp5)
print_any(temp7)